import type { ModelConfig } from "@/types/ai";

export const DEFAULT_MODELS: ModelConfig[] = [
  {
    id: "deepseek-chat",
    provider: "openrouter",
    modelId: "deepseek/deepseek-chat",
    displayName: "DeepSeek Chat",
    tier: "simple",
    enabled: true,
    priority: 1,
    costPer1kInput: 0.00014,
    costPer1kOutput: 0.00028,
    maxTokens: 4096,
  },
  {
    id: "qwen-7b",
    provider: "openrouter",
    modelId: "qwen/qwen-2.5-7b-instruct",
    displayName: "Qwen 2.5 7B",
    tier: "simple",
    enabled: true,
    priority: 2,
    costPer1kInput: 0.00004,
    costPer1kOutput: 0.0001,
    maxTokens: 4096,
  },
  {
    id: "mistral-small",
    provider: "openrouter",
    modelId: "mistralai/mistral-small-3.1-24b-instruct",
    displayName: "Mistral Small",
    tier: "medium",
    enabled: true,
    priority: 1,
    costPer1kInput: 0.0001,
    costPer1kOutput: 0.0003,
    maxTokens: 8192,
  },
  {
    id: "llama-70b",
    provider: "openrouter",
    modelId: "meta-llama/llama-3.3-70b-instruct",
    displayName: "Llama 3.3 70B",
    tier: "medium",
    enabled: true,
    priority: 2,
    costPer1kInput: 0.00012,
    costPer1kOutput: 0.0003,
    maxTokens: 8192,
  },
  {
    id: "claude-sonnet",
    provider: "openrouter",
    modelId: "anthropic/claude-sonnet-4",
    displayName: "Claude Sonnet",
    tier: "complex",
    enabled: true,
    priority: 1,
    costPer1kInput: 0.003,
    costPer1kOutput: 0.015,
    maxTokens: 16384,
  },
  {
    id: "gpt-4o",
    provider: "openrouter",
    modelId: "openai/gpt-4o",
    displayName: "GPT-4o",
    tier: "complex",
    enabled: true,
    priority: 2,
    costPer1kInput: 0.0025,
    costPer1kOutput: 0.01,
    maxTokens: 16384,
  },
  {
    id: "gemini-pro",
    provider: "openrouter",
    modelId: "google/gemini-2.5-pro-preview",
    displayName: "Gemini 2.5 Pro",
    tier: "complex",
    enabled: true,
    priority: 3,
    costPer1kInput: 0.00125,
    costPer1kOutput: 0.01,
    maxTokens: 16384,
  },
];

export const TOOL_TIER_MAP: Record<string, "simple" | "medium" | "complex"> = {
  "research-proposal": "complex",
  "literature-review": "complex",
  dissertation: "complex",
  paraphrase: "simple",
  grammar: "simple",
  rewrite: "simple",
  summarize: "medium",
  "abstract-generator": "medium",
  "problem-statement": "medium",
  "research-questions": "simple",
  "research-objectives": "simple",
  hypothesis: "simple",
  methodology: "complex",
  "research-gap": "medium",
  "discussion-chapter": "complex",
  "conclusion-chapter": "medium",
  "data-analysis-plan": "complex",
  "assistant-chat": "medium",
};
